package cn.ypj.wowsrankbackend.entity;

public class UserInfo {

    public class Pvp{
        private int maxFragsByMain;
        private int battlesCount512;
        private int battlesCount510;
        private int hitsBySkip;
        private int maxSuppressionsCountVehicle;
        private int hitsByAtba;
        private int shotsByMain;
        private int hitsByRocket;
        private int maxFragsByMainVehicle;
        private int maxFragsByTpdVehicle;
        private int shipsSpotted;
        private int hitsByBomb;
        private int maxScoutingDamage;
        private int premiumExp;
        private int droppedCapturePoints;
        private int maxFragsVehicle;
        private int maxFragsByDbomb;
        private int controlCapturedPoints;
        private int maxPremiumExpVehicle;
        private int maxPlanesKilled;
        private int maxExpVehicle;
        private int battlesCount;
        private int planesKilled;
        private int damageDealtToBuildings;
        private int fragsByTpd;
        private int maxShipsSpotted;
        private int artAgro;
        private int maxFragsByRam;
        private int maxTotalAgroVehicle;
        private int battlesCount0711;
        private int maxFragsByRamVehicle;
        private int shotsByTbomb;
        private int originalExp;
        private int frags;
        private int maxFragsByPlanes;
        private int fragsByPlanes;
        private int maxTotalAgro;
        private int shotsByTpd;
        private int capturePoints;
        private int fragsByRam;
        private int shotsByBomb;
        private int fragsByDbomb;
        private int maxSuppressionsCount;
        private int suppressionsCount;
        private int maxPlanesKilledVehicle;
        private int maxDamageDealtToBuildings;
        private int maxDamageDealtToBuildingsVehicle;
        private int maxDamageDealtVehicle;
        private int shotsByRocket;
        private int maxFragsByDbombVehicle;
        private int survived;
        private int scoutingDamage;
        private int maxShipsSpottedVehicle;
        private int fragsByAtba;
        private int shotsBySkip;
        private int controlDroppedPoints;
        private int maxDamageDealt;
        private int maxFragsByTpd;
        private int maxPremiumExp;
        private int hitsByTpd;
        private int maxFragsByAtba;
        private int tpdAgro;
        private int maxScoutingDamageVehicle;
        private int teamControlCapturedPoints;
        private int wins;
        private int losses;
        private int hitsByMain;
        private int winAndSurvived;
        private int damageDealt;
        private int battlesCount078;
        private int fragsByMain;
        private int teamControlDroppedPoints;
        private int maxFrags;
        private int exp;
        private int maxExp;
        private int battlesCount0910;
        private int hitsByTbomb;
        private int maxFragsByAtbaVehicle;
        private int maxFragsByPlanesVehicle;
        private int shotsByAtba;


    }


    public class Basic{
        private int levelingTier;
        private int createdAt;
        private int levelingPoints;
        private int karma;
        private int lastBattleTime;

    }
    public class PvpSolo{
        private int maxFragsByMain;
        private int battlesCount512;
        private int battlesCount510;
        private int hitsBySkip;
        private int maxSuppressionsCountVehicle;
        private int hitsByAtba;
        private int shotsByMain;
        private int hitsByRocket;
        private int maxFragsByMainVehicle;
        private int maxFragsByTpdVehicle;
        private int shipsSpotted;
        private int hitsByBomb;
        private int maxScoutingDamage;
        private int premiumExp;
        private int droppedCapturePoints;
        private int maxFragsVehicle;
        private int maxFragsByDbomb;
        private int controlCapturedPoints;
        private int maxPremiumExpVehicle;
        private int maxPlanesKilled;
        private int maxExpVehicle;
        private int battlesCount;
        private int planesKilled;
        private int damageDealtToBuildings;
        private int fragsByTpd;
        private int maxShipsSpotted;
        private int artAgro;
        private int maxFragsByRam;
        private int maxTotalAgroVehicle;
        private int battlesCount0711;
        private int maxFragsByRamVehicle;
        private int shotsByTbomb;
        private int originalExp;
        private int frags;
        private int maxFragsByPlanes;
        private int fragsByPlanes;
        private int maxTotalAgro;
        private int shotsByTpd;
        private int capturePoints;
        private int fragsByRam;
        private int shotsByBomb;
        private int fragsByDbomb;
        private int maxSuppressionsCount;
        private int suppressionsCount;
        private int maxPlanesKilledVehicle;
        private int maxDamageDealtToBuildings;
        private int maxDamageDealtToBuildingsVehicle;
        private int maxDamageDealtVehicle;
        private int shotsByRocket;
        private int maxFragsByDbombVehicle;
        private int survived;
        private int scoutingDamage;
        private int maxShipsSpottedVehicle;
        private int fragsByAtba;
        private int shotsBySkip;
        private int controlDroppedPoints;
        private int maxDamageDealt;
        private int maxFragsByTpd;
        private int maxPremiumExp;
        private int hitsByTpd;
        private int maxFragsByAtba;
        private int tpdAgro;
        private int maxScoutingDamageVehicle;
        private int teamControlCapturedPoints;
        private int wins;
        private int losses;
        private int hitsByMain;
        private int winAndSurvived;
        private int damageDealt;
        private int battlesCount078;
        private int fragsByMain;
        private int teamControlDroppedPoints;
        private int maxFrags;
        private int exp;
        private int maxExp;
        private int battlesCount0910;
        private int hitsByTbomb;
        private int maxFragsByAtbaVehicle;
        private int maxFragsByPlanesVehicle;
        private int shotsByAtba;


    }
    public class RankSolo{
        private int maxFragsByMain;
        private int battlesCount512;
        private int battlesCount510;
        private int hitsBySkip;
        private int maxSuppressionsCountVehicle;
        private int hitsByAtba;
        private int shotsByMain;
        private int hitsByRocket;
        private int maxFragsByMainVehicle;
        private int maxFragsByTpdVehicle;
        private int shipsSpotted;
        private int hitsByBomb;
        private int maxScoutingDamage;
        private int premiumExp;
        private int droppedCapturePoints;
        private int maxFragsVehicle;
        private int maxFragsByDbomb;
        private int controlCapturedPoints;
        private int maxPremiumExpVehicle;
        private int maxPlanesKilled;
        private int maxExpVehicle;
        private int battlesCount;
        private int planesKilled;
        private int damageDealtToBuildings;
        private int fragsByTpd;
        private int maxShipsSpotted;
        private int artAgro;
        private int maxFragsByRam;
        private int maxTotalAgroVehicle;
        private int battlesCount0711;
        private int maxFragsByRamVehicle;
        private int shotsByTbomb;
        private int originalExp;
        private int frags;
        private int maxFragsByPlanes;
        private int fragsByPlanes;
        private int maxTotalAgro;
        private int shotsByTpd;
        private int capturePoints;
        private int fragsByRam;
        private int shotsByBomb;
        private int fragsByDbomb;
        private int maxSuppressionsCount;
        private int suppressionsCount;
        private int maxPlanesKilledVehicle;
        private int maxDamageDealtToBuildings;
        private int maxDamageDealtToBuildingsVehicle;
        private int maxDamageDealtVehicle;
        private int shotsByRocket;
        private int maxFragsByDbombVehicle;
        private int survived;
        private int scoutingDamage;
        private int maxShipsSpottedVehicle;
        private int fragsByAtba;
        private int shotsBySkip;
        private int controlDroppedPoints;
        private int maxDamageDealt;
        private int maxFragsByTpd;
        private int maxPremiumExp;
        private int hitsByTpd;
        private int maxFragsByAtba;
        private int tpdAgro;
        private int maxScoutingDamageVehicle;
        private int teamControlCapturedPoints;
        private int wins;
        private int losses;
        private int hitsByMain;
        private int winAndSurvived;
        private int damageDealt;
        private int battlesCount078;
        private int fragsByMain;
        private int teamControlDroppedPoints;
        private int maxFrags;
        private int exp;
        private int maxExp;
        private int battlesCount0910;
        private int hitsByTbomb;
        private int maxFragsByAtbaVehicle;
        private int maxFragsByPlanesVehicle;
        private int shotsByAtba;


    }
    public class PvpDiv2{
        private int maxFragsByMain;
        private int battlesCount512;
        private int battlesCount510;
        private int hitsBySkip;
        private int maxSuppressionsCountVehicle;
        private int hitsByAtba;
        private int shotsByMain;
        private int hitsByRocket;
        private int maxFragsByMainVehicle;
        private int maxFragsByTpdVehicle;
        private int shipsSpotted;
        private int hitsByBomb;
        private int maxScoutingDamage;
        private int premiumExp;
        private int droppedCapturePoints;
        private int maxFragsVehicle;
        private int maxFragsByDbomb;
        private int controlCapturedPoints;
        private int maxPremiumExpVehicle;
        private int maxPlanesKilled;
        private int maxExpVehicle;
        private int battlesCount;
        private int planesKilled;
        private int damageDealtToBuildings;
        private int fragsByTpd;
        private int maxShipsSpotted;
        private int artAgro;
        private int maxFragsByRam;
        private int maxTotalAgroVehicle;
        private int battlesCount0711;
        private int maxFragsByRamVehicle;
        private int shotsByTbomb;
        private int originalExp;
        private int frags;
        private int maxFragsByPlanes;
        private int fragsByPlanes;
        private int maxTotalAgro;
        private int shotsByTpd;
        private int capturePoints;
        private int fragsByRam;
        private int shotsByBomb;
        private int fragsByDbomb;
        private int maxSuppressionsCount;
        private int suppressionsCount;
        private int maxPlanesKilledVehicle;
        private int maxDamageDealtToBuildings;
        private int maxDamageDealtToBuildingsVehicle;
        private int maxDamageDealtVehicle;
        private int shotsByRocket;
        private int maxFragsByDbombVehicle;
        private int survived;
        private int scoutingDamage;
        private int maxShipsSpottedVehicle;
        private int fragsByAtba;
        private int shotsBySkip;
        private int controlDroppedPoints;
        private int maxDamageDealt;
        private int maxFragsByTpd;
        private int maxPremiumExp;
        private int hitsByTpd;
        private int maxFragsByAtba;
        private int tpdAgro;
        private int maxScoutingDamageVehicle;
        private int teamControlCapturedPoints;
        private int wins;
        private int losses;
        private int hitsByMain;
        private int winAndSurvived;
        private int damageDealt;
        private int battlesCount078;
        private int fragsByMain;
        private int teamControlDroppedPoints;
        private int maxFrags;
        private int exp;
        private int maxExp;
        private int battlesCount0910;
        private int hitsByTbomb;
        private int maxFragsByAtbaVehicle;
        private int maxFragsByPlanesVehicle;
        private int shotsByAtba;

    }
    public class PvpDiv3{
        private int maxFragsByMain;
        private int battlesCount512;
        private int battlesCount510;
        private int hitsBySkip;
        private int maxSuppressionsCountVehicle;
        private int hitsByAtba;
        private int shotsByMain;
        private int hitsByRocket;
        private int maxFragsByMainVehicle;
        private int maxFragsByTpdVehicle;
        private int shipsSpotted;
        private int hitsByBomb;
        private int maxScoutingDamage;
        private int premiumExp;
        private int droppedCapturePoints;
        private int maxFragsVehicle;
        private int maxFragsByDbomb;
        private int controlCapturedPoints;
        private int maxPremiumExpVehicle;
        private int maxPlanesKilled;
        private int maxExpVehicle;
        private int battlesCount;
        private int planesKilled;
        private int damageDealtToBuildings;
        private int fragsByTpd;
        private int maxShipsSpotted;
        private int artAgro;
        private int maxFragsByRam;
        private int maxTotalAgroVehicle;
        private int battlesCount0711;
        private int maxFragsByRamVehicle;
        private int shotsByTbomb;
        private int originalExp;
        private int frags;
        private int maxFragsByPlanes;
        private int fragsByPlanes;
        private int maxTotalAgro;
        private int shotsByTpd;
        private int capturePoints;
        private int fragsByRam;
        private int shotsByBomb;
        private int fragsByDbomb;
        private int maxSuppressionsCount;
        private int suppressionsCount;
        private int maxPlanesKilledVehicle;
        private int maxDamageDealtToBuildings;
        private int maxDamageDealtToBuildingsVehicle;
        private int maxDamageDealtVehicle;
        private int shotsByRocket;
        private int maxFragsByDbombVehicle;
        private int survived;
        private int scoutingDamage;
        private int maxShipsSpottedVehicle;
        private int fragsByAtba;
        private int shotsBySkip;
        private int controlDroppedPoints;
        private int maxDamageDealt;
        private int maxFragsByTpd;
        private int maxPremiumExp;
        private int hitsByTpd;
        private int maxFragsByAtba;
        private int tpdAgro;
        private int maxScoutingDamageVehicle;
        private int teamControlCapturedPoints;
        private int wins;
        private int losses;
        private int hitsByMain;
        private int winAndSurvived;
        private int damageDealt;
        private int battlesCount078;
        private int fragsByMain;
        private int teamControlDroppedPoints;
        private int maxFrags;
        private int exp;
        private int maxExp;
        private int battlesCount0910;
        private int hitsByTbomb;
        private int maxFragsByAtbaVehicle;
        private int maxFragsByPlanesVehicle;
        private int shotsByAtba;

    }
    public class Statistics{
        private Pvp pvp;
        private RankInfo rankInfo;
        private Basic basic;
        private PvpSolo pvpSolo;
        private RankSolo rankSolo;
        private PvpDiv2 pvpDiv2;
        private PvpDiv3 pvpDiv3;


    }
    public class Slots{

    }
    public class DogTag{
        private int dollId;
        private Slots slots;
    }
    public class 2023619512{
        private Statistics statistics;
        private String name;
        private int createdAt;
        private int activatedAt;
        private boolean visibilitySettings;
        private DogTag dogTag;


    }
    public class Data{
        private 2023619512 2023619512;

        public 2023619512 get2023619512(){
            return 2023619512;
        }
        public void set2023619512(2023619512 input){
            this.2023619512 = input;
        }
    }
    public class MyClassName{
        private Data data;

        public Data getData(){
            return data;
        }
        public void setData(Data input){
            this.data = input;
        }
    }

}
