package model;

public class UserInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.UID
     *
     * @mbg.generated Fri Mar 17 15:50:42 CST 2023
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.USER_NAME
     *
     * @mbg.generated Fri Mar 17 15:50:42 CST 2023
     */
    private String userName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.UID
     *
     * @return the value of user_info.UID
     *
     * @mbg.generated Fri Mar 17 15:50:42 CST 2023
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.UID
     *
     * @param uid the value for user_info.UID
     *
     * @mbg.generated Fri Mar 17 15:50:42 CST 2023
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.USER_NAME
     *
     * @return the value of user_info.USER_NAME
     *
     * @mbg.generated Fri Mar 17 15:50:42 CST 2023
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.USER_NAME
     *
     * @param userName the value for user_info.USER_NAME
     *
     * @mbg.generated Fri Mar 17 15:50:42 CST 2023
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }
}